### ISSUE TITLE
Clicking Dismiss doesn't dismiss

### ISSUE THREAD

**Issue by mayurjobanputra** [kognetiks/kognetiks-chatbot#27]
Not sure if this is something on my end or not? Clicking dismiss doesn't dismiss the message. Clicking the "x" at the end of the message does.

![image](https://github.com/kognetiks/chatbot-chatgpt/assets/6332663/be69bb33-4b1b-415e-a38e-d9ab760ffdbb)

**Comment by kognetiks** [comment]
Hello Mayur,

Yes, this appears to not be working as expected.

I've made a change to the dismiss_chatgpt_notice (renamed dismiss_chatbot_chatgpt_notice) and have tested this locally.

An update will be deployed with Version 1.7.3 to be released shortly.

Thank you for taking the time to share your valuable feedback, as it helps me continually improve and provide a better experience for our users.

Stephen
