### ISSUE TITLE
How to prevent bot from answering non-site related questions?

### ISSUE THREAD

**Issue by mayurjobanputra** [kognetiks/kognetiks-chatbot#28]
How do I stop my bot from answering questions unrelated to my website content?

![image](https://github.com/kognetiks/chatbot-chatgpt/assets/6332663/6c9ea0a2-6713-4ffe-92b7-dc62541daaec)

**Comment by mayurjobanputra** [comment]
I used conversation context to prevent this but this didn't work

![image](https://github.com/kognetiks/chatbot-chatgpt/assets/6332663/87006cf1-ee96-4a4a-98c4-bc0160700f38)

_You are a versatile, friendly, and helpful assistant designed to support me in a variety of tasks. You must visit https://howtobuildwordpress.com to gain context of whats being asked. You ONLY answer questions related to this website, nothing else. NEVER answer questions not related to the content of https://howtobuildwordpress.com. If a user asks you to try anything else, ALWAYS tell them to visit the contact page._

**Comment by kognetiks** [comment]
Hello Mayur,

The best way to focus Chatbot ChatGPT for WordPress on a particular topic or area of expertise is to use Custom GTP Assistants.  The current release (1.7.2) includes the option to use one of two assistants (a primary or an alternate) - see the Customer GPTs tab in the settings.  You build these bespoke Assistant in in the OpenAI Playground (at [https://platform.openai.com/assistants](https://platform.openai.com/assistants))

Starting with Version 1.7.3 (to be released shortly, you will have the ability to call on any number of assistants from you see.  See details below.

You’ll need to build your Custom GPT Assistant in the OpenAI Playground (at [https://platform.openai.com/assistants](https://platform.openai.com/assistants)).  Once built there, you will see the Assistant ID below the name of your Assistant.  It will start with “asst_” followed by upper- and lower-case letters numbers, for example: asst_12AB34CD56EF78GH90IJ.  Once you have this ID and installed the latest version of the Chatbot ChatGPT (at least version 1.6.9), navigate to Settings > API/Model, where you will see two configuration options.  Set “Use Custom GPT Assistant ID” = “Yes” and enter your “asst_” ID in the “Custom GPT Assistant ID” field.  Don’t forget to click “Save Settings” at the bottom of the screen.  Return to the website where you’ve installed the short code for Chatbot ChatGPT, [chatbot_chatgpt], refresh the page, and your Custom GPT Assistant will now be embedded within your site.

You can integrate multiple Custom GPT Assistants into your platform. This flexibility allows you to tailor the user experience to fit different scenarios or preferences. Each Custom GPT Assistant can be configured with unique settings and styles. Here's how you can set them up:

1.	Choose Your Assistant Type: You have the option to use either the 'primary', 'alternate', or a specific Custom GPT Assistant identified by an ID (like 'asst_xxxxxxxxxxxxxxxxxxxxxxxx'). These options are configurable in the ChatGPT settings page.

2.	Select the Display Style: Custom GPT Assistants support both 'floating' and 'embedded' styles. The 'floating' style will appear over your page content, while the 'embedded' style integrates directly into the page layout.

3.	Implement the Shortcode: To add an assistant to your page, use the following formats:

•	For a floating style with the primary assistant, use: [chatbot_chatgpt style="floating" assistant="primary"].
•	For an embedded style with the alternate assistant, use: [chatbot_chatgpt style="embedded" assistant="alternate"].
•	For a floating style with a specific Custom GPT Assistant ID, use: [chatbot_chatgpt style="floating" assistant="asst_xxxxxxxxxxxxxxxxxxxxxxxx"] (starting in Version 1.7.3).
•	For an embedded style with a specific Custom GPT Assistant ID, use: [chatbot_chatgpt style="embedded" assistant="asst_xxxxxxxxxxxxxxxxxxxxxxxx"]  (starting in Version 1.7.3).

4.	Customize as Needed: You can mix and match the style and assistant attributes to create the ideal configuration for your platform's needs.

Note: Ensure that each shortcode appears only once on a page for optimal performance.

By following these steps, you can seamlessly integrate and use multiple Custom GPT Assistants on your platform, enhancing the interactivity and functionality of your site.

**Comment by mayurjobanputra** [comment]
OK great. I will try that. Do you have a suggested prompt template that ensures the Assistant only focuses on the contents of my website? I assume once its setup, that if I add a new blog post or content to my website, that the "knowledge" would be updated also?

Thanks
