### ISSUE TITLE
floating scroll problem

### ISSUE THREAD

**Issue by pvanallen** [kognetiks/kognetiks-chatbot#52]
I'm using [chatbot style="floating" assistant="primary"] and have a problem where the bot window does not scroll properly. Once you have gotten a few responses from the chatbot, you can't see the text entry field anymore and you can't scroll to it. This is on both Safari and Chrome on a Mac and iPhone.
<img width="295" alt="chatbot_scrolling_problem" src="https://github.com/kognetiks/kognetiks-chatbot/assets/1456334/6fa6210d-7625-4fc9-9e98-5220d0204941">

**Comment by kognetiks** [comment]
Hello Philip,

This sometimes happens when the shortcode is wrapped within bold html elements.

Check to make sure that it is not accidently surround by <b> and </b> or <strong> and </strong>.

If you find that it is, removed the emphasis and save the content.  Be sure the use CTRL-SHFT R to refresh the page.

If this doesn't fix it, please let me know.

Stephen

**Comment by kognetiks** [comment]
Hello Philip,

Just updated my response as I forgot to put in the esc characters.

Check to make sure that it is not accidently surround by \<b\> and \</b\> or \<strong\> and \</strong\>.

Stephen

**Comment by pvanallen** [comment]
Thanks Stephen - that was it. Fixed now! I think that the <b> tags were there because I was copy/pasting from the settings page where the shortcodes are bolded - that carried over when I pasted the shortcode into a block. Could I suggest that maybe you remove the bolding in the settings panel for the assistant shortcodes to prevent this from recurring for others?

**Comment by pvanallen** [comment]
<img width="924" alt="Pasted_Image_3_15_24__9_16 AM" src="https://github.com/kognetiks/kognetiks-chatbot/assets/1456334/68699196-48be-4104-a754-3fc6d14c3710">

**Comment by kognetiks** [comment]
Hello Philip,

Will do!!!  I'll adjust for the next release.  Glad your problem is solved.

Stephen
