### ISSUE TITLE
Assistant works with retrieval in playground, but not in plugin

### ISSUE THREAD

**Issue by levfo** [kognetiks/kognetiks-chatbot#57]
Plugin will not access the information retrieved by assistant from uploaded file.

**Comment by levfo** [comment]
Corrected by disabling / enabling the assistant in settings. Opened page in incognito and tried again. Still does not work if I'm not in incognito.. but it's progress.

**Comment by kognetiks** [comment]
Hello Levfo,

Here are a couple of things to check on to see if everything is working as expected.

Have you tried a shortcode calling the assistant directly?

[chatbot style=embedded assistant=asst_xxxxxxxxxxxxxxxxxxxxxxx]

Also, what model is your assistant set to use (in platform.openai.com/assistants)?

I've found the models earlier than gpt-4-turbo-preview are fincky with retireval via the API.

Somtimes something simple like a typo in the assistant id or using quotes can be problematic.

I also ran into a circumstance where the installation on a hosting provider that didn't allow for passed parameters on shortcodes.  Go figure!

The results were similar to what you're reporting - works in playground, doesn't work with chatbot.

Stephen

**Comment by levfo** [comment]
It is working fine now.. I did reference the assistant directly, now I am using "primary" and it is working fine still. My guess is that maybe the site was cached with the old assistant id, or since it had previous knowledge of our chat before the reference information was added, it just repeated answers? I will continue to test and see if it happens more. Thanks for the quick response!
