### ISSUE TITLE
how to user question limit 

### ISSUE THREAD

**Issue by SingaravelC** [kognetiks/kognetiks-chatbot#70]
we need first two question free without login more then two question need to login with payment for Kognetiks Chatbot plugin.

**Comment by kognetiks** [comment]
Hello SingaravelC,

An excellent idea.  A bit difficult to implement without a persistent cookie deployed to non-logged in visitors.

There is a global setting to limit anyone's inquiry count.

I'll have to see what I can do for logged-in, visitor, etc.

I like the idea will have something in version 2.0.1 - to be pushed to production shortly.

Stephen

**Comment by kognetiks** [comment]
Please use V2.0.1.  It now includes:

= 2.0.1 Interaction Limiting =
* Expanded interaction limiting into limits for visitors and logged-in users.
  - See the Chatbot Settings > API/Model tab
  - Chatbot Daily Message Limit - this is for logged-in users
  - Visitor Daily Message Limit - this is for casual visitors

**Comment by SingaravelC** [comment]
user limit is working, thank you.  
we need first two question free without login more then two question need to login with payment for Chatbot plugin in your suggestion. please send the any plugin name. i am kindly request

**Comment by SingaravelC** [comment]
> user limit is working, thank you. we need first two question free without login more then two question need to login with payment for Chatbot plugin in your suggestion. please send the any plugin name. i am kindly request

hi sir. please reply me

**Comment by SingaravelC** [comment]
ok , thank you for your support

**Comment by SingaravelC** [comment]
![Screenshot (77)](https://github.com/kognetiks/kognetiks-chatbot/assets/161044694/7d6d414f-7894-45b0-b58d-75d11dcead5a)
![Screenshot (78)](https://github.com/kognetiks/kognetiks-chatbot/assets/161044694/3a5bfdc6-68d8-4a75-83b8-525129072571)

When asking a question in open ai assistant, it gives the answer only from the answer in the file, but if there is no answer, it says "not relevant to tax". But Kognetiks Chatbot plugin also gives answer to the question asked without plugin. To solve these issues somehow. I have uploaded two sample files for you

**Comment by SingaravelC** [comment]
> ![Screenshot (77)](https://private-user-images.githubusercontent.com/161044694/338873348-7d6d414f-7894-45b0-b58d-75d11dcead5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzk5NjcsIm5iZiI6MTcxODE3OTY2NywicGF0aCI6Ii8xNjEwNDQ2OTQvMzM4ODczMzQ4LTdkNmQ0MTRmLTc4OTQtNDViMC1iNThkLTc1ZDExZGNlYWQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODA3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzM4MzQ4MTI2OThhNDcxMTlhNTViNGFiMDUzZTAyNmNjZjNjMjNjMGY0MGVjNjZhNzAyNDEyYzNhNzk3MmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P5lz8zZrZKJhst6gwdduxrmo3v0VHYC3u0wK8_SqZuk) ![Screenshot (78)](https://private-user-images.githubusercontent.com/161044694/338873360-3a5bfdc6-68d8-4a75-83b8-525129072571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzk5NjcsIm5iZiI6MTcxODE3OTY2NywicGF0aCI6Ii8xNjEwNDQ2OTQvMzM4ODczMzYwLTNhNWJmZGM2LTY4ZDgtNGE3NS04M2I4LTUyNTEyOTA3MjU3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODA3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmRjZmUwZGRmYTY3NDI4MmJhNGVhYWNmNzE3MTVmMjA5NGU0ZmFmM2UxZWQ5N2ViMWFmMWFjYWJlMTRiYzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QZ_XhZHbGN_z57DFPUMnsTKBaQqB2BuI-CQpjYmBdEI)
> 
> When asking a question in open ai assistant, it gives the answer only from the answer in the file, but if there is no answer, it says "not relevant to tax". But Kognetiks Chatbot plugin also gives answer to the question asked without plugin. To solve these issues somehow. I have uploaded two sample files for you

please solve the issues. i am kindly request

**Comment by SingaravelC** [comment]
pl

> ![Screenshot (77)](https://private-user-images.githubusercontent.com/161044694/338873348-7d6d414f-7894-45b0-b58d-75d11dcead5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzk5NjcsIm5iZiI6MTcxODE3OTY2NywicGF0aCI6Ii8xNjEwNDQ2OTQvMzM4ODczMzQ4LTdkNmQ0MTRmLTc4OTQtNDViMC1iNThkLTc1ZDExZGNlYWQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODA3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzM4MzQ4MTI2OThhNDcxMTlhNTViNGFiMDUzZTAyNmNjZjNjMjNjMGY0MGVjNjZhNzAyNDEyYzNhNzk3MmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P5lz8zZrZKJhst6gwdduxrmo3v0VHYC3u0wK8_SqZuk) ![Screenshot (78)](https://private-user-images.githubusercontent.com/161044694/338873360-3a5bfdc6-68d8-4a75-83b8-525129072571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzk5NjcsIm5iZiI6MTcxODE3OTY2NywicGF0aCI6Ii8xNjEwNDQ2OTQvMzM4ODczMzYwLTNhNWJmZGM2LTY4ZDgtNGE3NS04M2I4LTUyNTEyOTA3MjU3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODA3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmRjZmUwZGRmYTY3NDI4MmJhNGVhYWNmNzE3MTVmMjA5NGU0ZmFmM2UxZWQ5N2ViMWFmMWFjYWJlMTRiYzE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QZ_XhZHbGN_z57DFPUMnsTKBaQqB2BuI-CQpjYmBdEI)
> 
> When asking a question in open ai assistant, it gives the answer only from the answer in the file, but if there is no answer, it says "not relevant to tax". But Kognetiks Chatbot plugin also gives answer to the question asked without plugin. To solve these issues somehow. I have uploaded two sample files for you

please reply me sir

**Comment by kognetiks** [comment]
Hello SsingaravelC,

Here are a couple of things to check to see what might be going on.

If you have not turned on Conversation Logging, please go to the Chatbot Settings, then click on the Reporting tab, then scroll down and set "Enable Converation Logging" to "On".

![image](https://github.com/kognetiks/kognetiks-chatbot/assets/128191215/eee3df28-6403-4cfd-872f-b45b4a735c97)

Then return to the chatbot and ask you question again.

Assuming you get the same answer, then come back to the Reporting tab and click the "Download Conversation Data" button.

![image](https://github.com/kognetiks/kognetiks-chatbot/assets/128191215/e0278d5b-8ed1-4100-ba2c-efa5e53cdb1b)

This will download the data to a CSV file which you can examine using Excel or Sheets or another text based editor.

It should have some data like this:

![image](https://github.com/kognetiks/kognetiks-chatbot/assets/128191215/28c92313-4c9a-4e4d-a038-4fa98ac13e5d)

Column H will have the assistant_id, and column I will have the Assistant_name.

If Columns G, H and I are blank, then the shortcode is not being handled correctly and tells us that the is a error in the shortcode.

If Columns G, H and I have content, the shortcode is working as expected and tells us that the issue is with the instructions in the Assistant.

In either case, your findings should inform us as to where to look next.

I away your response.

Stephen

**Comment by SingaravelC** [comment]
![Screenshot (81)](https://github.com/kognetiks/kognetiks-chatbot/assets/161044694/f8d05962-6856-41c4-8df7-aaa996c39e97)
![Screenshot (82)](https://github.com/kognetiks/kognetiks-chatbot/assets/161044694/2d4721ac-3259-4668-b07e-deb6257546bc)
[Chatbot-ChatGPT-Conversation-Logs-2024-06-13 (2).csv](https://github.com/user-attachments/files/15814279/Chatbot-ChatGPT-Conversation-Logs-2024-06-13.2.csv)

Hi sir,
         I did as you said. But it didn't work. I have uploaded the document for your reference, please check it. I request you to reply me.

**Comment by kognetiks** [comment]
Hello [SingaravelC](https://github.com/SingaravelC),

I took a look at the CSV.  I see that the Assistant ID is not being populated.

![image](https://github.com/kognetiks/kognetiks-chatbot/assets/128191215/def38e46-1c17-4fa0-b986-d5ec3af9a053)

Let's try a couple of things.

First, can you creat a new page?

Use this short code:

[chatbot style=embedded assistant=asst_rtR15zFAxs42WrJ9wOEjruaa]

On that page, add a shortcode block, it should look like this:

![image](https://github.com/kognetiks/kognetiks-chatbot/assets/128191215/537102c0-9d6d-4a11-b8e1-350b2f24deea)

Save the page as "Draft", we don't need to publish it just yet.

Then view the draft page.

The chatbot should open, enter your prompt, then submit the prompt.

After the answer. is returned, inspect the conversation log again.

If the Assistant ID is present, then everything is working as expected.

If it is still not present, then there is likely a caching problem with your server.

You can find some related info on cache control here:

https://wpengine.com/support/web-rules-engine/#Header_Rules

Let me know what you determine.

Stephen

**Comment by SingaravelC** [comment]
Hi Sir,
         we need first two question free without login more then two question need to login with payment for Kognetiks Chatbot plugin.

**Comment by kognetiks** [comment]
Hello [SingaravelC](https://github.com/SingaravelC),

Open the Chatbot Settings, then click on the API/Model tab, there you will find two settings, Chatbot Daily Message Limit and Visitor Daily Message Limit.

Set the Visitor Daily Message Limit to 2, then click Save Settings at the bottom of the page.

![image](https://github.com/user-attachments/assets/d3ea7813-55b4-4783-b598-663abe842ef1)

This would limit the visitor to two inquiries per day.

I'll add a time limit setting so it can be reset by day or never reset.

Since the chatbot doesn't log IP addresses of visitors, this approach will work until the visitor clears cache and cookies.

So, it's not fool proof.

Let me know if this will work for you in the interim.

Regards,

Stephen

**Comment by SingaravelC** [comment]
Hi Sir,
         Even though I have set a 2-question limit for visitors, they are still able to ask more than two or three questions, and the system is responding. Your plugin is not enforcing the visitor question limit. Please check on your end for the plugin issue.

**Comment by SingaravelC** [comment]
Hi Sir,
          we need first two question free without login more then two question need to login with payment for Kognetiks Chatbot plugin.

**Comment by SingaravelC** [comment]
are you there mr.kognetiks

**Comment by SingaravelC** [comment]
hello mr.kognetiks are you there

**Comment by kognetiks** [comment]
Please update to V2.1.7 as this should resolve this problem.
